config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      :omniauth_callbacks => "user/omniauth_callbacks"
  }

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root 'pages#landing'

  resources :projects
  resources :teams

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ApplicationRecord
  has_many :team_in_projects
  has_many :teams, through: :team_in_projects

  accepts_nested_attributes_for :teams
end

app/controllers/project/activities_controller.rb
class Project::ActivitiesController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @activity = Project.find(params[:project_id]).activities.all
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def new
    @project = Project.find(params[:id])
    @activity = Activity.new
  end

  def update
    @project = Project.find(params[:id])
    @activity = Activity.find(params[:id])
    if @activity.update_attributes(activity_params)
      @activity.save
      redirect_to project_activities_path(@project)
    else
      render :edit
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:yesterday, :today, :problems, :date)
  end

end

app/controllers/projects_controller.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = User.find_by_id(current_user.id).teams.joins(:projects).map(&:projects)
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
    @team = Team.new
    @project.teams.build
    @role = Role.new
    @project.teams.first.roles.build
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      @project.teams.first.user_in_teams.first.update_attributes(user_id: current_user.id, admin: true)
      redirect_to root_path
    else
      @project.errors.messages.each do |c|
        flash[:alert] = c[1].first
      end
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, teams_attributes: [ :name, roles_attributes: [ :name, :description ]])
  end
end

app/helpers/project/activities_helper.rb
module Project::ActivitiesHelper
end

app/helpers/projects_helper.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="field">
    <%= f.label 'name' %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-blue' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="header-small">
  <div class="wrapper">
    <div class="triangle">
      <h1>Get started with your projects</h1>
    </div>
  </div>
</div>
<div class="content">
  <div class="container-sm">
    <h1>My Projects</h1>
    <div class="panel panel-default">
      <div class="panel-heading">
      </div>
      <table class="table">
        <thead>
          <th>Project Name</th>
          <th></th>
        </thead>
        <tbody>
          <% if @projects.each do |f| %>
            <tr>
              <td>
                <%= f.first.name %>
              </td>
              <td>
                <%= link_to (content_tag :span, (), class: 'fa fa-eye fa-fw') + ' view ' + f.first.name, project_path(f.first), class: 'btn btn-sm btn-blue', title: 'Show'  %>
                <%= link_to (content_tag :span, (), class: 'fa fa-remove fa-fw') + ' delete ' + f.first.name, project_path(f.first), class: 'btn btn-sm btn-red', title: 'Delete', method: :delete, data: { :confirm => "Are you sure?" } %>
              </td>
            </tr>
          <% end.empty? %>
            <tr> <td>
              You don't have any projects yet.
            </td> </tr>
          <% end %>

        </tbody>
      </table>
      <div class="panel-footer">
      </div>
    </div>
    <%= link_to (content_tag :span, (), class: 'fa fa-plus fa-fw') + " New Project", new_project_path , class: 'btn btn-green' %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="content">
  <div class="container-sm">
    <%= link_to content_tag(:i, (), class: 'fa fa-arrow-left') + ' Back', projects_path, class: 'btn btn-blue' %>
    <h1>Setup a new project</h1>
    <%= form_for @project do |f| %>
      <div class="well">
        <h3>Project Settings</h3>
        <div class="field">
          <%= f.label 'Project name' %>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label 'Project description' %>
          <%= f.text_area :description, rows: 5 %>
        </div>
      </div>
      <%= f.fields_for :teams, @team do |t| %>
        <div class="well">
          <h3>Team settings</h3>
          <div class="field">
            <%= t.label 'Team name' %>
            <%= t.text_field :name %>
          </div>
        </div>
        <%= t.fields_for :roles, @role do |r| %>
          <div class="well">
            <h3>Role settings</h3>
            <div class="field">
              <%= r.label 'Role name' %>
              <%= r.text_field :name %>
            </div>
            <div class="field">
              <%= r.label 'Role description' %>
              <%= r.text_area :description, rows: 2 %>
            </div>
          </div>
        <% end %>
      <% end %>
      <div class="actions">
        <%= f.submit class: 'btn btn-blue' %>
      </div>
    <% end %>
  </div>

</div>

app/views/projects/show.html.erb
<div class="content">
  <div class="container-sm">
    <%= link_to content_tag(:i, (), class: 'fa fa-arrow-left') + ' Back', projects_path, class: 'btn btn-blue' %>
    <h1><%= @project.name %> Dashboard</h1>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>My Teams</h3>
      </div>
      <table class="table">
        <thead>
          <th>Team Name</th>
          <th>Your Role</th>
          <th>Team Members</th>
          <th></th>
        </thead>
        <tbody>
          <% @project.teams.each do |u| %>
            <%# next if u.users.find_by_id(current_user.id) == nil %>
            <tr>
              <td>
                <%= u.name %>
              </td>
              <td>
                <% if u.users.find_by_id(current_user.id) %>
                  <%= u.roles.joins(:users).first.name %>
                <% else %>
                  You're not a part of this team
                <% end %>
              </td>
              <td>
                <%= u.users.count %>
              </td>
              <td>
                <%= link_to 'View', team_path(u) %>
                <%= link_to (content_tag :span, (), class: 'fa fa-pencil fa-fw'), '#', class: 'btn btn-sm btn-blue', title: 'Edit'  %>
                <%= link_to (content_tag :span, (), class: 'fa fa-remove fa-fw'), '#', class: 'btn btn-sm btn-red', title: 'Delete', method: :delete, data: { :confirm => "Are you sure?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="panel-footer">
        <%= link_to (content_tag :span, (), class: 'fa fa-plus fa-fw') + ' Add Team', '#', class: 'btn btn-sm btn-green', title: 'Add'  %>
      </div>
    </div>
</div>